name: Run Python Scripts and Commit Results

on:
  schedule:
    # 毎週月曜日の午前6時（JST）に実行。UTCでは前日の21時なので、'0 21 * * 0'と記述
    - cron: "0 21 * * 0"
  workflow_dispatch:

jobs:
  run-scripts-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.6" # Pythonのバージョンを指定

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas  # 必要な依存関係をインストール

      - name: Run Python scripts
        run: |
          python 1.castles-list-cre.py
          python 2.castles-data-get.py
          python 3.csv2geojson.py

      - name: Commit files
        run: |
          git config --local user.email "yohei.shiwaku@gmail.com"
          git config --local user.name "shiwaku"
          git add .
          git commit -m "Update data files" || echo "No changes to commit"
          git pull --rebase
          git push
